#!/bin/bash
#SBATCH --job-name=rl_atari
#SBATCH --output=atari_env.%j # Name of stdout output file (%j expands to %jobId)
#SBATCH --time=0-12:00:00
#SBATCH --partition=gpu-4-a100
#SBATCH --mail-user=andre_meneses2001@hotmail.com
#SBATCH --mail-type=ALL
#SBATCH --account=shell
#SBATCH --hint=compute_bound
#SBATCH --cpus-per-task=64

#SBATCH --gpus=1                        # total number of GPUs required by this job.

##SBATCH --mem=0

module load compilers/nvidia/cuda/11.7
export TORCH_CUDA_VERSION=cu117

python3 grid_search_cnn.py
